version: "3.7"

services:
  streamlit_calc:
    build:
      context: streamlit_calc
    ports:
      - "8501"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/lb-webserver_pro_combined.crt:/etc/pki/nginx/lb-webserver_pro_combined.crt:ro
      - ./config/private/private.key:/etc/pki/nginx/private/private.key:ro
      - ./config/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - streamlit_calc
    ports:
      - "8501:8501"
    restart: always